FROM golang:1.23-alpine AS builder
WORKDIR /app

COPY . .

RUN go build -o master ./master

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/master/master /app/master
EXPOSE 8080
CMD ["/app/master"]
